/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Random;
import modele.Instance;
import modele.TypeProduit;

/**
 *
 * @author jules
 */
public class InstanceView extends javax.swing.JFrame {

    /**
     * Creates new form InstanceView
     */
    public InstanceView() {
        this.initComponents();
        this.initialisationFenetre();
    }
     private void initialisationFenetre() {
        this.setVisible(true);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int) screenSize.getWidth();
        int height = (int) screenSize.getHeight();
        this.setLocation(0,0);
        this.setSize( width, height-35);
        this.setBackground(Color.BLUE);
        this.getContentPane();
        
    }
    /**
     * Fonction prise de stack overflow pour avoir une couleur aléatoire
     * https://stackoverflow.com/questions/4246351/creating-random-colour-in-java
     * @return Color
     */
    public Color RandomColor(){
       Random rand = new Random();
       float r = rand.nextFloat();
       float g = rand.nextFloat();
       float b = rand.nextFloat();
       
       return new Color(r, g, b);
    }

    public InstanceView(Instance instance) {
        this();
        this.setTitle("Instance : "+instance.getNomInstance());
        int oldGroup=-1; int actualGroup=-1;
        Color couleur = null;
        for(TypeProduit p : instance.getSetProduits()){
            actualGroup = p.getGrpProduit();
            System.out.println("old : "+ oldGroup);
            System.out.println("actuel : "+ actualGroup);
            //si le groupe du produit n'est pas le même que celui d'avant
            if(oldGroup == -1 || oldGroup != actualGroup){
                couleur = RandomColor();
                System.out.println("iffffffffffffffffff");
            }
            oldGroup = actualGroup;
            p.setCouleur(couleur);
        }
        this.zoneGraph.setListB(instance.getSetBox());
        
        
        for( TypeProduit p : instance.getSetProduits())
        //System.out.println(""+ p.getLproduit());
        
        
        this.zoneGraph.setListP(instance.getSetProduits());
        this.zoneGraph.repaint();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zoneGraph = new vue.PanelView();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout zoneGraphLayout = new javax.swing.GroupLayout(zoneGraph);
        zoneGraph.setLayout(zoneGraphLayout);
        zoneGraphLayout.setHorizontalGroup(
            zoneGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );
        zoneGraphLayout.setVerticalGroup(
            zoneGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(zoneGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(zoneGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(92, 92, 92))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstanceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstanceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstanceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstanceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstanceView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vue.PanelView zoneGraph;
    // End of variables declaration//GEN-END:variables
}
