/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import modele.TypeBox;
import modele.TypeProduit;

/**
 *
 * @author agpou
 */
public class PanelView extends javax.swing.JPanel {
    public Collection<TypeBox> listB = new HashSet<>();
    public List<TypeProduit> listP = new ArrayList<>();
    private final int echelle=3;
    
    /**
     * Creates new form Test
     */
    public PanelView() {
        initComponents();
    }

    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        int i=0;
        int x = 5;
        int y = 50;
        int sizeScreen = this.getWidth();
        int maxHeight = 0;
        System.out.println("size screen :"+sizeScreen);
        
        g.setFont(new Font("Calibri", Font.PLAIN, 35));
        g.drawString("Les Box", sizeScreen/2, 25);
        g.drawLine(5,35, sizeScreen-5, 35);
        
        for(TypeBox b : listB){
            if(x+b.getLbox()/echelle >= sizeScreen){
                x = 5;
                y+=maxHeight+10;
                maxHeight = 0;
            }
            g.setColor(b.getCouleur());
            g.fillRect(x,y,b.getLbox()/echelle,b.getHbox()/echelle);
            if(maxHeight < b.getHbox()/echelle )  maxHeight = b.getHbox()/echelle;
            x+=(b.getLbox()/echelle)+10;
        }
        System.out.println("Affichage des box réussi !!");
        System.out.println("y = "+y);
        
        g.setColor(Color.black);
        //g.drawLine(5,y+maxHeight+20, sizeScreen-5, y+maxHeight+20);
        g.setFont(new Font("Calibri", Font.PLAIN, 35));
        g.drawString("Les Produits", sizeScreen/2, y+maxHeight+50);
        g.drawLine(5,y+maxHeight+70, sizeScreen-5, y+maxHeight+70);
        
        y= y+maxHeight+80;
        x = 5;
        maxHeight = 0;

        for(TypeProduit p : listP){
            g.setColor(p.getCouleur());
            int nbProd = p.getNBproduit();
                if(x+p.getLproduit()/echelle >= sizeScreen){
                    x = 5;
                    y+=maxHeight+10;
                    maxHeight = 0;
                }
                g.fillRect(x,y,p.getLproduit()/echelle,p.getHproduit()/echelle);
                if(maxHeight < p.getHproduit()/echelle )  maxHeight = p.getHproduit()/echelle;
                x+=(p.getLproduit()/echelle)+10;
        }
        System.out.println("Affichage des produits réussi !!");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public Collection<TypeBox> getListB() {
        return listB;
    }
    public void setListB(Collection<TypeBox> listB) {
        this.listB = listB;
    }
    public List<TypeProduit> getListP() {
        return listP;
    }
    public void setListP(List<TypeProduit> listP) {
        this.listP = listP;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
