/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.util.ArrayDeque;
import java.util.Collection;
import java.util.Deque;
import java.util.HashSet;
import java.util.Random;
import modele.TypeBox;
import modele.TypeProduit;

/**
 *
 * @author agpou
 */
public class PanelPile extends javax.swing.JPanel {
        private int echelle=3;
        public Collection<TypeProduit> listP = new HashSet<>();
        public Collection<TypeBox> listB = new HashSet<>();
        public Collection<TypeProduit> listBis= new HashSet<>();

    
    /**
     * Creates new form PanelPile
     */
    public PanelPile() {
        initComponents();
    }

    public Color RandomColor(){
       Random rand = new Random();
       float r = rand.nextFloat();
       float g = rand.nextFloat();
       float b = rand.nextFloat();
       
       return new Color(r, g, b);
    }
    
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        int x = 50;
        int y = 50;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int) screenSize.getWidth();
        int height = (int) screenSize.getHeight();
        
        this.setSize(width-35, height-35);
        int sizeScreen = this.getWidth();

        System.out.println("size screen :"+sizeScreen);
        
        Deque<TypeProduit> pileProd = new ArrayDeque<TypeProduit>();
        Deque<TypeProduit> pileProd2 = new ArrayDeque<TypeProduit>();

        TypeProduit p1 = new TypeProduit("P001",100,100,1);    
        TypeProduit p2 = new TypeProduit("P002",220,80,1);
        TypeProduit p3 = new TypeProduit("P003",260,120,1);
        pileProd.push(p3); pileProd.push(p2); pileProd.push(p1);

        TypeProduit p4 = new TypeProduit("P004",160,70,1);    
        TypeProduit p5 = new TypeProduit("P005",220,50,1);
        TypeProduit p6 = new TypeProduit("P006",300,90,1);
        pileProd2.push(p6); pileProd2.push(p5); pileProd2.push(p4);
        
        
        TypeBox b1 = new TypeBox("B001",600,320,8);
        
        g.setColor(Color.blue);
        g.drawRect(x,y,b1.getLbox(),b1.getHbox());
        y+=b1.getHbox();
        int size1 = pileProd.size();

        int maxW = 0;
        for(int i=0; i<size1;i++){
            TypeProduit p = pileProd.getLast();
            if(p.getLproduit() > maxW) maxW = p.getLproduit();
            System.out.println(p.getId());
            g.setColor(RandomColor());
            y-=p.getHproduit();
            g.fillRect(x+1, y,p.getLproduit(), p.getHproduit());
            pileProd.removeLastOccurrence(p);
        }
        
        int size2 = pileProd2.size();
        y= 50 +b1.getHbox();
        x+=maxW;
        for(int i=0; i<size2;i++){
           // System.out.println("size pile : "+pileProd.size());
            TypeProduit p = pileProd2.getLast();
            System.out.println(p.getId());
            g.setColor(RandomColor());
            y-=p.getHproduit();
            g.fillRect(x+1, y,p.getLproduit(), p.getHproduit());
            pileProd2.removeLastOccurrence(p);
        }
        
        
        
        


        
        
        
        
        
        
        
        /*g.setFont(new Font("Calibri", Font.PLAIN, 35));
        g.drawString("Les Box", sizeScreen/2, 25);
        g.drawLine(5,35, sizeScreen-5, 35);*/
        

       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
