/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Toolkit;
import modele.ContenuBox;
import modele.PileProduit;
import modele.Solution;
import modele.TypeProduit;

/**
 *
 * @author agpou
 */
public class PanelPile extends javax.swing.JPanel {
        private int echelle=2;
        private Solution s;
        private long tempsTotal;
    
    /**
     * Creates new form PanelPile
     */
    public PanelPile() {
        initComponents();
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        int x = 50;
        int y = 70;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int) screenSize.getWidth();
        int height = (int) screenSize.getHeight();
 
        int maxW = 0,maxHeight =0, positionRef=0, y2=0, x2=0;
        
        //Affichage d'un titre avec la solution et le coût
        g.setFont(new Font("Calibri", Font.PLAIN, 40));
        g.drawString("Solution de "+s.getInstanceSolution().getNomInstance()+"               coût: "+s.getPrixFinal()+"€         Temps: "+tempsTotal+"ms",width/6,40);
        g.drawLine(5,50, width-5,50);

        for(ContenuBox cb : s.getListeContenuBox()){

            //System.out.println("ContenuBox");
            g.setColor(Color.blue);
            //si la box dépasse en largeur de l'écran du pc 
            if(x+cb.getMaTypeBox().getLbox()/echelle > width-35){
                y = positionRef + maxHeight+10;
                x=50;
                maxHeight=0;
                //System.out.println("passer la ");
            }
            g.drawRect(x,y-1,cb.getMaTypeBox().getLbox()/echelle,(cb.getMaTypeBox().getHbox()/echelle+1));
            if(maxHeight < cb.getMaTypeBox().getHbox()/echelle )  maxHeight = cb.getMaTypeBox().getHbox()/echelle;

            positionRef = y;
            y = positionRef+cb.getMaTypeBox().getHbox()/echelle;
            y2 = y;
            x2=x;
            for(PileProduit pileProd : cb.getMaListeProduits()){
                //System.out.println("PileProduit");
                for(TypeProduit p : pileProd.getPileProduits()){
                    //System.out.println("TypeProduit");
                    if(p.getLproduit()/echelle> maxW) maxW = p.getLproduit()/echelle;
                    //System.out.println(p.getId());
                    y-=p.getHproduit()/echelle;
                    g.setColor(p.getCouleur());
                    g.fillRect(x+1, y,p.getLproduit()/echelle, p.getHproduit()/echelle);
                    g.setColor(Color.black);
                    g.drawRect(x+1, y,p.getLproduit()/echelle, p.getHproduit()/echelle);
                }
                y= y2;
                x+=maxW;
                maxW =0;
            }
            x = x2+cb.getMaTypeBox().getLbox()/echelle+10;
            y=positionRef;
        }
        

        Dimension dim = new Dimension(this.getWidth(),y+maxHeight+15);
        this.setPreferredSize(dim);
        this.revalidate();
    }
    
    /**************** GETTER AND SETTER ******************/
    public void setSolutionADessiner(Solution s){
        this.s=s;
    }
    public long getTempsTotal() {
        return tempsTotal;
    }
    public void setTempsTotal(long tempsTotal) {
        this.tempsTotal = tempsTotal;
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
