/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.util.ArrayDeque;
import java.util.Collection;
import java.util.Deque;
import java.util.HashSet;
import java.util.Random;
import modele.Algorithme;
import modele.ContenuBox;
import modele.Instance;
import modele.PileProduit;
import modele.Solution;
import modele.TypeBox;
import modele.TypeProduit;

/**
 *
 * @author agpou
 */
public class PanelPile extends javax.swing.JPanel {
        private int echelle=3;
        public Collection<TypeProduit> listP = new HashSet<>();
        public Collection<TypeBox> listB = new HashSet<>();
        public Collection<TypeProduit> listBis= new HashSet<>();
        public Solution s;
    
    /**
     * Creates new form PanelPile
     */
    public PanelPile() {
        initComponents();
    }

    public Color RandomColor(){
       Random rand = new Random();
       float r = rand.nextFloat();
       float g = rand.nextFloat();
       float b = rand.nextFloat();
       
       return new Color(r, g, b);
    }
    
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        int x = 50;
        int y = 50;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int) screenSize.getWidth();
        int height = (int) screenSize.getHeight();
        
        this.setSize(width-35, height-35);
        int sizeScreen = this.getWidth();

        System.out.println("size screen :"+sizeScreen);
        
       
        
        
        
        
        

        /*g.setColor(Color.blue);
        g.drawRect(x,y,b1.getLbox(),b1.getHbox());
        y+=b1.getHbox();*/
        int maxW = 0,maxHeight =0, positionRef=0, y2=0, x2=0;
        for(ContenuBox cb : s.getListeContenuBox()){

            //System.out.println("ContenuBox");
            g.setColor(Color.blue);
            //si la box dépasse en largeur de l'écran du pc 
            if(x+cb.getMaTypeBox().getLbox() > sizeScreen){
                y = positionRef + maxHeight+10;
                x=50;
                maxHeight=0;
                //System.out.println("passer la ");
            }
            g.drawRect(x,y-1,cb.getMaTypeBox().getLbox(),cb.getMaTypeBox().getHbox()+1);
            if(maxHeight < cb.getMaTypeBox().getHbox())  maxHeight = cb.getMaTypeBox().getHbox();

            positionRef = y;
            y = positionRef+cb.getMaTypeBox().getHbox();
            y2 = y;
            x2=x;
            for(PileProduit pileProd : cb.getMaListeProduits()){
                //System.out.println("PileProduit");
                for(TypeProduit p : pileProd.getPileProduits()){
                    //System.out.println("TypeProduit");
                    if(p.getLproduit() > maxW) maxW = p.getLproduit();
                    //System.out.println(p.getId());
                    g.setColor(p.getCouleur());
                    y-=p.getHproduit();
                    g.fillRect(x+1, y,p.getLproduit(), p.getHproduit());
                    
                }
                y= y2;
                x+=maxW;
                maxW =0;
            }
            x = x2+cb.getMaTypeBox().getLbox()+10;
            y=positionRef;
            System.out.println("position y1 : "+y);
        }
        Dimension dim = new Dimension(this.getWidth(),1000);
        this.setPreferredSize(dim);
        this.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
